# golangci-lint configuration
# For full options see: https://golangci-lint.run/usage/configuration/

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Field order optimizations often reduce readability

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/bbockelm/golang-classads

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam  # Value struct is intentionally passed by value
      - ifElseChain  # if-else chains are often clearer than switches
      - unnamedResult  # Named results not always needed for simple returns

  revive:
    confidence: 0.8

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - revive
    - misspell
    - unparam
    - unconvert
    - exportloopref

  disable:
    - typecheck  # Disabled because of generated parser code

issues:
  exclude-rules:
    # Exclude generated parser code from most checks
    - path: parser/y\.go
      linters:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - unused
        - gocritic
        - revive
        - unparam
        - unconvert

    # Exclude test files from certain checks
    - path: _test\.go
      linters:
        - errcheck
        - unparam

    # Exclude safe type conversions in evaluator (type is checked before calling)
    - path: classad/evaluator\.go
      text: "Error return value of.*Value.*is not checked"
      linters:
        - errcheck

    # Exclude safe type conversions in functions (type is checked before calling)
    - path: classad/functions\.go
      text: "Error return value of.*Value.*is not checked"
      linters:
        - errcheck

    # Exclude safe type conversions in matchclassad (type is checked before calling)
    - path: classad/matchclassad\.go
      text: "Error return value of.*Value.*is not checked"
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - vendor
