# golangci-lint configuration
# For full options see: https://golangci-lint.run/usage/configuration/

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/bbockelm/golang-classads

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

  revive:
    confidence: 0.8

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - revive
    - misspell
    - unparam
    - unconvert
    - exportloopref

  disable:
    - typecheck  # Disabled because of generated parser code

issues:
  exclude-rules:
    # Exclude generated parser code from most checks
    - path: parser/y\.go
      linters:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - unused
        - gocritic
        - revive
        - unparam
        - unconvert

    # Exclude test files from certain checks
    - path: _test\.go
      linters:
        - errcheck
        - unparam

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - vendor
