version: "2"
run:
  tests: true
linters:
  enable:
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      disabled-checks:
        - hugeParam
        - ifElseChain
        - unnamedResult
        - ptrToRefParam
      enabled-tags:
        - diagnostic
        - style
        - performance
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      confidence: 0.8
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocritic
          - govet
          - ineffassign
          - revive
          - staticcheck
          - unconvert
          - unparam
          - unused
        path: parser/y\.go
      - linters:
          - errcheck
          - unparam
        path: _test\.go
      - linters:
          - errcheck
        path: examples/
      - linters:
          - errcheck
        path: classad/evaluator\.go
        text: Error return value of.*Value.*is not checked
      - linters:
          - errcheck
        path: classad/functions\.go
        text: Error return value of.*Value.*is not checked
      - linters:
          - errcheck
        path: classad/matchclassad\.go
        text: Error return value of.*Value.*is not checked
    paths:
      - bin
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/PelicanPlatform/classad
  exclusions:
    generated: lax
    paths:
      - bin
      - vendor
      - third_party$
      - builtin$
      - examples$
