// Code generated by goyacc -o parser/y.go -p yy parser/classad.y. DO NOT EDIT.

//line parser/classad.y:2
package parser

import (
	__yyfmt__ "fmt"

	"github.com/PelicanPlatform/classad/ast"
) //line parser/classad.y:2

//line parser/classad.y:10
type yySymType struct {
	yys      int
	node     ast.Node
	expr     ast.Expr
	classad  *ast.ClassAd
	attr     *ast.AttributeAssignment
	attrs    []*ast.AttributeAssignment
	exprlist []ast.Expr
	str      string
	integer  int64
	real     float64
	boolean  bool
}

const IDENTIFIER = 57346
const STRING_LITERAL = 57347
const INTEGER_LITERAL = 57348
const REAL_LITERAL = 57349
const BOOLEAN_LITERAL = 57350
const UNDEFINED = 57351
const ERROR = 57352
const ELVIS = 57353
const OR = 57354
const AND = 57355
const EQ = 57356
const NE = 57357
const IS = 57358
const ISNT = 57359
const LE = 57360
const GE = 57361
const LSHIFT = 57362
const RSHIFT = 57363
const URSHIFT = 57364
const UNARY = 57365

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING_LITERAL",
	"INTEGER_LITERAL",
	"REAL_LITERAL",
	"BOOLEAN_LITERAL",
	"UNDEFINED",
	"ERROR",
	"ELVIS",
	"'?'",
	"':'",
	"OR",
	"AND",
	"'|'",
	"'^'",
	"'&'",
	"EQ",
	"NE",
	"IS",
	"ISNT",
	"'<'",
	"'>'",
	"LE",
	"GE",
	"LSHIFT",
	"RSHIFT",
	"URSHIFT",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARY",
	"'!'",
	"'~'",
	"'.'",
	"'['",
	"'('",
	"']'",
	"';'",
	"'='",
	"')'",
	"'{'",
	"'}'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser/classad.y:274

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 142

var yyAct = [...]int8{
	76, 13, 74, 23, 21, 18, 25, 19, 24, 108,
	22, 12, 107, 31, 38, 36, 37, 39, 40, 41,
	16, 113, 80, 106, 109, 9, 20, 10, 8, 9,
	112, 72, 3, 17, 73, 68, 69, 70, 71, 27,
	26, 60, 61, 48, 79, 28, 29, 47, 42, 33,
	62, 63, 64, 84, 34, 15, 85, 46, 90, 91,
	92, 93, 4, 45, 97, 98, 82, 103, 94, 95,
	96, 99, 100, 101, 104, 105, 86, 87, 88, 89,
	83, 7, 111, 110, 31, 38, 36, 37, 39, 40,
	41, 31, 38, 36, 37, 39, 40, 41, 7, 102,
	81, 67, 57, 58, 59, 77, 7, 1, 75, 114,
	27, 26, 115, 43, 14, 44, 28, 29, 78, 42,
	33, 53, 54, 55, 56, 34, 42, 33, 65, 66,
	6, 30, 34, 32, 35, 5, 49, 50, 51, 52,
	11, 2,
}

var yyPact = [...]int16{
	-7, -32768, -32768, 94, -13, -32768, -32768, -16, -32768, 102,
	80, -32768, -32768, -32768, 101, 48, 41, 30, 25, 117,
	98, 75, 11, 18, -32768, 90, 80, 80, 80, 80,
	-32768, -9, -32768, 80, 80, -32768, -32768, -32768, -32768, -32768,
	-32768, -32768, 77, 9, 80, 80, 80, 80, 80, 80,
	80, 80, 80, 80, 80, 80, 80, 80, 80, 80,
	80, 80, 80, 80, 80, 95, 80, 87, -32768, -32768,
	-32768, -32768, 80, -21, -34, -38, -32768, -17, -32768, 70,
	80, 48, 41, 30, 25, 117, 98, 98, 98, 98,
	75, 75, 75, 75, 11, 11, 11, 18, 18, -32768,
	-32768, -32768, -32768, -11, -32768, -23, -32768, -32768, 80, -32768,
	80, -32768, -32768, -32768, -32768, -32768,
}

var yyPgo = [...]uint8{
	0, 141, 134, 62, 130, 0, 133, 131, 6, 8,
	3, 10, 4, 26, 7, 5, 33, 20, 55, 114,
	1, 108, 2, 107,
}

var yyR1 = [...]int8{
	0, 23, 1, 1, 2, 2, 3, 3, 3, 4,
	5, 20, 20, 20, 19, 19, 18, 18, 17, 17,
	16, 16, 15, 15, 14, 14, 14, 14, 14, 13,
	13, 13, 13, 13, 12, 12, 12, 12, 11, 11,
	11, 10, 10, 10, 10, 9, 9, 9, 9, 9,
	8, 8, 8, 8, 8, 7, 7, 7, 7, 7,
	6, 6, 6, 6, 6, 6, 22, 22, 21, 21,
}

var yyR2 = [...]int8{
	0, 1, 3, 2, 3, 2, 1, 3, 2, 3,
	1, 1, 5, 4, 1, 3, 1, 3, 1, 3,
	1, 3, 1, 3, 1, 3, 3, 3, 3, 1,
	3, 3, 3, 3, 1, 3, 3, 3, 1, 3,
	3, 1, 3, 3, 3, 1, 2, 2, 2, 2,
	1, 3, 4, 3, 4, 1, 1, 3, 3, 1,
	1, 1, 1, 1, 1, 1, 0, 1, 1, 3,
}

var yyChk = [...]int16{
	-32768, -23, -1, 39, -3, 41, -4, 4, 41, 42,
	43, -4, -5, -20, -19, -18, -17, -16, -15, -14,
	-13, -12, -11, -10, -9, -8, 31, 30, 36, 37,
	-7, 4, -6, 40, 45, -2, 6, 7, 5, 8,
	9, 10, 39, 12, 14, 15, 16, 17, 18, 19,
	20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
	30, 31, 32, 33, 34, 38, 39, 11, -9, -9,
	-9, -9, 40, -5, -22, -21, -5, -3, 41, -5,
	13, -18, -17, -16, -15, -14, -13, -13, -13, -13,
	-12, -12, -12, -12, -11, -11, -11, -10, -10, -9,
	-9, -9, 4, -5, -8, -22, 44, 46, 47, 41,
	13, -20, 41, 44, -5, -20,
}

var yyDef = [...]int8{
	0, -2, 1, 0, 0, 3, 6, 0, 2, 8,
	0, 7, 9, 10, 11, 14, 16, 18, 20, 22,
	24, 29, 34, 38, 41, 45, 0, 0, 0, 0,
	50, 56, 55, 0, 66, 59, 60, 61, 62, 63,
	64, 65, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 46, 47,
	48, 49, 66, 0, 0, 67, 68, 0, 5, 0,
	0, 15, 17, 19, 21, 23, 25, 26, 27, 28,
	30, 31, 32, 33, 35, 36, 37, 39, 40, 42,
	43, 44, 51, 0, 53, 0, 57, 58, 0, 4,
	0, 13, 52, 54, 69, 12,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 36, 3, 3, 3, 34, 18, 3,
	40, 44, 32, 30, 47, 31, 38, 33, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 13, 42,
	23, 43, 24, 12, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 39, 3, 41, 17, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 45, 16, 46, 37,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	14, 15, 19, 20, 21, 22, 25, 26, 27, 28,
	29, 35,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:62
		{
			if lex, ok := yylex.(interface{ SetResult(ast.Node) }); ok {
				lex.SetResult(yyDollar[1].classad)
			}
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:71
		{
			yyVAL.classad = &ast.ClassAd{Attributes: yyDollar[2].attrs}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:73
		{
			yyVAL.classad = &ast.ClassAd{Attributes: []*ast.AttributeAssignment{}}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:78
		{
			yyVAL.classad = &ast.ClassAd{Attributes: yyDollar[2].attrs}
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:80
		{
			yyVAL.classad = &ast.ClassAd{Attributes: []*ast.AttributeAssignment{}}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:85
		{
			yyVAL.attrs = []*ast.AttributeAssignment{yyDollar[1].attr}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:87
		{
			yyVAL.attrs = append(yyDollar[1].attrs, yyDollar[3].attr)
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:89
		{
			yyVAL.attrs = yyDollar[1].attrs
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:94
		{
			yyVAL.attr = &ast.AttributeAssignment{Name: yyDollar[1].str, Value: yyDollar[3].expr}
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:99
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:104
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 12:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/classad.y:106
		{
			yyVAL.expr = &ast.ConditionalExpr{Condition: yyDollar[1].expr, TrueExpr: yyDollar[3].expr, FalseExpr: yyDollar[5].expr}
		}
	case 13:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/classad.y:108
		{
			yyVAL.expr = &ast.ElvisExpr{Left: yyDollar[1].expr, Right: yyDollar[4].expr}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:113
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:115
		{
			yyVAL.expr = &ast.BinaryOp{Op: "||", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:120
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:122
		{
			yyVAL.expr = &ast.BinaryOp{Op: "&&", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:127
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:129
		{
			yyVAL.expr = &ast.BinaryOp{Op: "|", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:134
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:136
		{
			yyVAL.expr = &ast.BinaryOp{Op: "^", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:141
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:143
		{
			yyVAL.expr = &ast.BinaryOp{Op: "&", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:148
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:150
		{
			yyVAL.expr = &ast.BinaryOp{Op: "==", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:152
		{
			yyVAL.expr = &ast.BinaryOp{Op: "!=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:154
		{
			yyVAL.expr = &ast.BinaryOp{Op: "is", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:156
		{
			yyVAL.expr = &ast.BinaryOp{Op: "isnt", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:161
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:163
		{
			yyVAL.expr = &ast.BinaryOp{Op: "<", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:165
		{
			yyVAL.expr = &ast.BinaryOp{Op: ">", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:167
		{
			yyVAL.expr = &ast.BinaryOp{Op: "<=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:169
		{
			yyVAL.expr = &ast.BinaryOp{Op: ">=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:174
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:176
		{
			yyVAL.expr = &ast.BinaryOp{Op: "<<", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:178
		{
			yyVAL.expr = &ast.BinaryOp{Op: ">>", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:180
		{
			yyVAL.expr = &ast.BinaryOp{Op: ">>>", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:185
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:187
		{
			yyVAL.expr = &ast.BinaryOp{Op: "+", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:189
		{
			yyVAL.expr = &ast.BinaryOp{Op: "-", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:194
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:196
		{
			yyVAL.expr = &ast.BinaryOp{Op: "*", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:198
		{
			yyVAL.expr = &ast.BinaryOp{Op: "/", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:200
		{
			yyVAL.expr = &ast.BinaryOp{Op: "%", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:205
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:207
		{
			yyVAL.expr = &ast.UnaryOp{Op: "-", Expr: yyDollar[2].expr}
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:209
		{
			yyVAL.expr = &ast.UnaryOp{Op: "+", Expr: yyDollar[2].expr}
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:211
		{
			yyVAL.expr = &ast.UnaryOp{Op: "!", Expr: yyDollar[2].expr}
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:213
		{
			yyVAL.expr = &ast.UnaryOp{Op: "~", Expr: yyDollar[2].expr}
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:218
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:220
		{
			yyVAL.expr = &ast.SelectExpr{Record: yyDollar[1].expr, Attr: yyDollar[3].str}
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/classad.y:222
		{
			yyVAL.expr = &ast.SubscriptExpr{Container: yyDollar[1].expr, Index: yyDollar[3].expr}
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:224
		{
			yyVAL.expr = &ast.ElvisExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/classad.y:226
		{
			yyVAL.expr = &ast.FunctionCall{Name: yyDollar[1].str, Args: yyDollar[3].exprlist}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:231
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:233
		{
			name, scope := ParseScopedIdentifier(yyDollar[1].str)
			yyVAL.expr = &ast.AttributeReference{Name: name, Scope: scope}
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:238
		{
			yyVAL.expr = ast.Parenthesize(yyDollar[2].expr)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:240
		{
			yyVAL.expr = &ast.ListLiteral{Elements: yyDollar[2].exprlist}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:242
		{
			yyVAL.expr = &ast.RecordLiteral{ClassAd: yyDollar[1].classad}
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:247
		{
			yyVAL.expr = &ast.IntegerLiteral{Value: yyDollar[1].integer}
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:249
		{
			yyVAL.expr = &ast.RealLiteral{Value: yyDollar[1].real}
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:251
		{
			yyVAL.expr = &ast.StringLiteral{Value: yyDollar[1].str}
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:253
		{
			yyVAL.expr = &ast.BooleanLiteral{Value: yyDollar[1].boolean}
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:255
		{
			yyVAL.expr = &ast.UndefinedLiteral{}
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:257
		{
			yyVAL.expr = &ast.ErrorLiteral{}
		}
	case 66:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/classad.y:262
		{
			yyVAL.exprlist = []ast.Expr{}
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:264
		{
			yyVAL.exprlist = yyDollar[1].exprlist
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:269
		{
			yyVAL.exprlist = []ast.Expr{yyDollar[1].expr}
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:271
		{
			yyVAL.exprlist = append(yyDollar[1].exprlist, yyDollar[3].expr)
		}
	}
	goto yystack /* stack new state and value */
}
