// Code generated by goyacc -o parser/y.go -p yy parser/classad.y. DO NOT EDIT.

//line parser/classad.y:2
package parser

import __yyfmt__ "fmt"

//line parser/classad.y:2

import (
	"github.com/PelicanPlatform/classad/ast"
)

//line parser/classad.y:10
type yySymType struct {
	yys      int
	node     ast.Node
	expr     ast.Expr
	classad  *ast.ClassAd
	attr     *ast.AttributeAssignment
	attrs    []*ast.AttributeAssignment
	exprlist []ast.Expr
	str      string
	integer  int64
	real     float64
	boolean  bool
}

const IDENTIFIER = 57346
const STRING_LITERAL = 57347
const INTEGER_LITERAL = 57348
const REAL_LITERAL = 57349
const BOOLEAN_LITERAL = 57350
const UNDEFINED = 57351
const ERROR = 57352
const OR = 57353
const AND = 57354
const EQ = 57355
const NE = 57356
const IS = 57357
const ISNT = 57358
const LE = 57359
const GE = 57360
const LSHIFT = 57361
const RSHIFT = 57362
const URSHIFT = 57363
const UNARY = 57364

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING_LITERAL",
	"INTEGER_LITERAL",
	"REAL_LITERAL",
	"BOOLEAN_LITERAL",
	"UNDEFINED",
	"ERROR",
	"'?'",
	"':'",
	"OR",
	"AND",
	"'|'",
	"'^'",
	"'&'",
	"EQ",
	"NE",
	"IS",
	"ISNT",
	"'<'",
	"'>'",
	"LE",
	"GE",
	"LSHIFT",
	"RSHIFT",
	"URSHIFT",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARY",
	"'!'",
	"'~'",
	"'.'",
	"'['",
	"'('",
	"']'",
	"';'",
	"'='",
	"')'",
	"'{'",
	"'}'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser/classad.y:273

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 35,
	1, 4,
	-2, 6,
	-1, 72,
	1, 3,
	-2, 5,
}

const yyPrivate = 57344

const yyLast = 144

var yyAct = [...]int8{
	71, 3, 5, 36, 69, 34, 12, 15, 16, 23,
	30, 28, 29, 31, 32, 33, 105, 76, 104, 112,
	103, 11, 111, 73, 110, 74, 68, 62, 64, 65,
	66, 10, 8, 13, 19, 18, 72, 73, 14, 75,
	20, 21, 37, 63, 25, 67, 9, 60, 61, 26,
	43, 82, 83, 84, 85, 23, 30, 28, 29, 31,
	32, 33, 99, 93, 94, 81, 95, 96, 97, 100,
	7, 37, 102, 78, 80, 107, 42, 106, 101, 109,
	19, 18, 86, 87, 88, 89, 20, 21, 79, 63,
	25, 90, 91, 92, 40, 26, 23, 30, 28, 29,
	31, 32, 33, 57, 58, 59, 113, 35, 55, 56,
	77, 114, 52, 53, 54, 48, 49, 50, 51, 41,
	108, 19, 18, 44, 45, 46, 47, 20, 21, 37,
	4, 25, 38, 98, 39, 1, 26, 70, 6, 17,
	22, 24, 27, 2,
}

var yyPact = [...]int16{
	92, -1000, -1000, -1000, 67, -1000, 121, 80, 104, 60,
	33, 105, 93, 86, 79, 72, -1000, 10, 51, 51,
	51, 51, -1000, 6, -1000, 51, 51, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -4, -1000, -1000, -17, 5, 51,
	51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
	51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
	129, 51, -1000, 38, -1000, -1000, -1000, 51, -23, -27,
	-30, -1000, -1000, 125, 51, 108, 51, 80, 104, 60,
	33, 105, 93, 93, 93, 93, 86, 86, 86, 86,
	79, 79, 79, 72, 72, -1000, -1000, -1000, -1000, -16,
	-18, -1000, -24, -1000, -1000, 51, -1000, -1000, 51, -1000,
	-1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 143, 142, 5, 3, 0, 141, 140, 139, 8,
	7, 38, 33, 6, 21, 31, 46, 32, 70, 138,
	2, 137, 4, 135,
}

var yyR1 = [...]int8{
	0, 23, 23, 1, 1, 2, 2, 3, 3, 3,
	4, 5, 20, 20, 20, 19, 19, 18, 18, 17,
	17, 16, 16, 15, 15, 14, 14, 14, 14, 14,
	13, 13, 13, 13, 13, 12, 12, 12, 12, 11,
	11, 11, 10, 10, 10, 10, 9, 9, 9, 9,
	9, 8, 8, 8, 8, 7, 7, 7, 7, 7,
	6, 6, 6, 6, 6, 6, 22, 22, 21, 21,
}

var yyR2 = [...]int8{
	0, 1, 1, 3, 2, 3, 2, 1, 3, 2,
	3, 1, 1, 5, 4, 1, 3, 1, 3, 1,
	3, 1, 3, 1, 3, 1, 3, 3, 3, 3,
	1, 3, 3, 3, 3, 1, 3, 3, 3, 1,
	3, 3, 1, 3, 3, 3, 1, 2, 2, 2,
	2, 1, 3, 4, 4, 1, 1, 3, 3, 1,
	1, 1, 1, 1, 1, 1, 0, 1, 1, 3,
}

var yyChk = [...]int16{
	-1000, -23, -1, -5, 38, -20, -19, -18, -17, -16,
	-15, -14, -13, -12, -11, -10, -9, -8, 30, 29,
	35, 36, -7, 4, -6, 39, 44, -2, 6, 7,
	5, 8, 9, 10, -3, 40, -4, 4, 11, 13,
	14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
	24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
	37, 38, -9, 38, -9, -9, -9, 39, -5, -22,
	-21, -5, 40, 41, 42, -5, 12, -18, -17, -16,
	-15, -14, -13, -13, -13, -13, -12, -12, -12, -12,
	-11, -11, -11, -10, -10, -9, -9, -9, 4, -5,
	-3, 40, -22, 43, 45, 46, -4, -5, 12, -20,
	40, 40, 43, -5, -20,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 0, 11, 12, 15, 17, 19,
	21, 23, 25, 30, 35, 39, 42, 46, 0, 0,
	0, 0, 51, 56, 55, 0, 66, 59, 60, 61,
	62, 63, 64, 65, 0, -2, 7, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 47, 0, 48, 49, 50, 66, 0, 0,
	67, 68, -2, 9, 0, 0, 0, 16, 18, 20,
	22, 24, 26, 27, 28, 29, 31, 32, 33, 34,
	36, 37, 38, 40, 41, 43, 44, 45, 52, 0,
	0, 6, 0, 57, 58, 0, 8, 10, 0, 14,
	53, 5, 54, 69, 13,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 35, 3, 3, 3, 33, 17, 3,
	39, 43, 31, 29, 46, 30, 37, 32, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 12, 41,
	22, 42, 23, 11, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 38, 3, 40, 16, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 44, 15, 45, 36,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 13,
	14, 18, 19, 20, 21, 24, 25, 26, 27, 28,
	34,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:57
		{
			if lex, ok := yylex.(interface{ SetResult(ast.Node) }); ok {
				lex.SetResult(yyDollar[1].classad)
			}
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:63
		{
			if lex, ok := yylex.(interface{ SetResult(ast.Node) }); ok {
				lex.SetResult(yyDollar[1].expr)
			}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:72
		{
			yyVAL.classad = &ast.ClassAd{Attributes: yyDollar[2].attrs}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:74
		{
			yyVAL.classad = &ast.ClassAd{Attributes: []*ast.AttributeAssignment{}}
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:79
		{
			yyVAL.classad = &ast.ClassAd{Attributes: yyDollar[2].attrs}
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:81
		{
			yyVAL.classad = &ast.ClassAd{Attributes: []*ast.AttributeAssignment{}}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:86
		{
			yyVAL.attrs = []*ast.AttributeAssignment{yyDollar[1].attr}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:88
		{
			yyVAL.attrs = append(yyDollar[1].attrs, yyDollar[3].attr)
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:90
		{
			yyVAL.attrs = yyDollar[1].attrs
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:95
		{
			yyVAL.attr = &ast.AttributeAssignment{Name: yyDollar[1].str, Value: yyDollar[3].expr}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:100
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:105
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 13:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/classad.y:107
		{
			yyVAL.expr = &ast.ConditionalExpr{Condition: yyDollar[1].expr, TrueExpr: yyDollar[3].expr, FalseExpr: yyDollar[5].expr}
		}
	case 14:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/classad.y:109
		{
			yyVAL.expr = &ast.ElvisExpr{Left: yyDollar[1].expr, Right: yyDollar[4].expr}
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:114
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:116
		{
			yyVAL.expr = &ast.BinaryOp{Op: "||", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:121
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:123
		{
			yyVAL.expr = &ast.BinaryOp{Op: "&&", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:128
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:130
		{
			yyVAL.expr = &ast.BinaryOp{Op: "|", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:135
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:137
		{
			yyVAL.expr = &ast.BinaryOp{Op: "^", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:142
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:144
		{
			yyVAL.expr = &ast.BinaryOp{Op: "&", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:149
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:151
		{
			yyVAL.expr = &ast.BinaryOp{Op: "==", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:153
		{
			yyVAL.expr = &ast.BinaryOp{Op: "!=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:155
		{
			yyVAL.expr = &ast.BinaryOp{Op: "is", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:157
		{
			yyVAL.expr = &ast.BinaryOp{Op: "isnt", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:162
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:164
		{
			yyVAL.expr = &ast.BinaryOp{Op: "<", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:166
		{
			yyVAL.expr = &ast.BinaryOp{Op: ">", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:168
		{
			yyVAL.expr = &ast.BinaryOp{Op: "<=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:170
		{
			yyVAL.expr = &ast.BinaryOp{Op: ">=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:175
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:177
		{
			yyVAL.expr = &ast.BinaryOp{Op: "<<", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:179
		{
			yyVAL.expr = &ast.BinaryOp{Op: ">>", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:181
		{
			yyVAL.expr = &ast.BinaryOp{Op: ">>>", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:186
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:188
		{
			yyVAL.expr = &ast.BinaryOp{Op: "+", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:190
		{
			yyVAL.expr = &ast.BinaryOp{Op: "-", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:195
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:197
		{
			yyVAL.expr = &ast.BinaryOp{Op: "*", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:199
		{
			yyVAL.expr = &ast.BinaryOp{Op: "/", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:201
		{
			yyVAL.expr = &ast.BinaryOp{Op: "%", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:206
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:208
		{
			yyVAL.expr = &ast.UnaryOp{Op: "-", Expr: yyDollar[2].expr}
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:210
		{
			yyVAL.expr = &ast.UnaryOp{Op: "+", Expr: yyDollar[2].expr}
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:212
		{
			yyVAL.expr = &ast.UnaryOp{Op: "!", Expr: yyDollar[2].expr}
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/classad.y:214
		{
			yyVAL.expr = &ast.UnaryOp{Op: "~", Expr: yyDollar[2].expr}
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:219
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:221
		{
			yyVAL.expr = &ast.SelectExpr{Record: yyDollar[1].expr, Attr: yyDollar[3].str}
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/classad.y:223
		{
			yyVAL.expr = &ast.SubscriptExpr{Container: yyDollar[1].expr, Index: yyDollar[3].expr}
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/classad.y:225
		{
			yyVAL.expr = &ast.FunctionCall{Name: yyDollar[1].str, Args: yyDollar[3].exprlist}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:230
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:232
		{
			name, scope := ParseScopedIdentifier(yyDollar[1].str)
			yyVAL.expr = &ast.AttributeReference{Name: name, Scope: scope}
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:237
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:239
		{
			yyVAL.expr = &ast.ListLiteral{Elements: yyDollar[2].exprlist}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:241
		{
			yyVAL.expr = &ast.RecordLiteral{ClassAd: yyDollar[1].classad}
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:246
		{
			yyVAL.expr = &ast.IntegerLiteral{Value: yyDollar[1].integer}
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:248
		{
			yyVAL.expr = &ast.RealLiteral{Value: yyDollar[1].real}
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:250
		{
			yyVAL.expr = &ast.StringLiteral{Value: yyDollar[1].str}
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:252
		{
			yyVAL.expr = &ast.BooleanLiteral{Value: yyDollar[1].boolean}
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:254
		{
			yyVAL.expr = &ast.UndefinedLiteral{}
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:256
		{
			yyVAL.expr = &ast.ErrorLiteral{}
		}
	case 66:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/classad.y:261
		{
			yyVAL.exprlist = []ast.Expr{}
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:263
		{
			yyVAL.exprlist = yyDollar[1].exprlist
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/classad.y:268
		{
			yyVAL.exprlist = []ast.Expr{yyDollar[1].expr}
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/classad.y:270
		{
			yyVAL.exprlist = append(yyDollar[1].exprlist, yyDollar[3].expr)
		}
	}
	goto yystack /* stack new state and value */
}
